/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                  '#00677f',
        'on-primary':               '#ffffff',
        'primary-container':        '#47b5d6',
        'on-primary-container':     '#004354',
        'primary-fixed':            '#b5ebff',
        'primary-fixed-dim':        '#6bd4f6',
        'primary-accent':           '#4bb8d9',
        'primary-strong':           '#00829f',
        'on-primary-fixed':         '#001f28',
        'on-primary-fixed-variant': '#004e60',
        'inverse-primary':          '#6bd4f6',
        'secondary':                '#585e6c',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#dde2f3',
        'on-secondary-container':   '#5e6473',
        'secondary-fixed':          '#dde2f3',
        'secondary-fixed-dim':      '#c1c6d7',
        'on-secondary-fixed':       '#161c27',
        'on-secondary-fixed-variant': '#414754',
        'tertiary':                 '#785900',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#d4a000',
        'on-tertiary-container':    '#4f3a00',
        'tertiary-fixed':           '#ffdf9e',
        'tertiary-fixed-dim':       '#fabd00',
        'on-tertiary-fixed':        '#261a00',
        'on-tertiary-fixed-variant':'#5b4300',
        'surface':                  '#f7fafc',
        'surface-bright':           '#f7fafc',
        'surface-dim':              '#d7dadc',
        'surface-container':        '#ebeef0',
        'surface-container-low':    '#f1f4f6',
        'surface-container-high':   '#e5e9eb',
        'surface-container-highest':'#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'surface-variant':          '#e0e3e5',
        'surface-tint':             '#00677f',
        'on-surface':               '#181c1e',
        'on-surface-variant':       '#3e484d',
        'inverse-surface':          '#2d3133',
        'inverse-on-surface':       '#eef1f3',
        'background':               '#f7fafc',
        'on-background':            '#181c1e',
        'outline':                  '#6e797e',
        'outline-variant':          '#bdc8cd',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':    ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        'unit':              '8px',
        'stack-sm':          '4px',
        'stack-md':          '12px',
        'stack-lg':          '24px',
        'container-margin':  '20px',
        'gutter':            '16px',
      },
      maxWidth: {
        container: '80rem',
      },
      boxShadow: {
        card:    '0px 4px 20px rgba(0,0,0,0.06)',
        overlay: '0px 12px 32px rgba(0,0,0,0.12)',
      },
    },
  },
  plugins: [],
};
